### ISSUE TITLE
Multi-Multi-ModelError

### ISSUE THREAD

**Issue by TTitscher** [BAMresearch/BayesianInference#2]
We currently have the option to combine multiple parameters to joint parameter lists and, accordingly, multiple model errors to a `MultiModelError`. 

Do we need another recursive layer around this to allow arbitrary combinations? If so, how? 

~~~
ME1(P1) \
ME2(P2)  | => MutliME1([P1, P2, P3]) \
ME3(P3) /                             | ==> MultiME3([P1, P2, P3, P4, P5] 
                                     /
ME4(P4) \ => MultiME2([P4, P5])  
ME5(P5) /              ||
                       \/
# OR       /  MultiME4([P6, P4, P5])
ME6(P6)  /
~~~

**Comment by joergfunger** [comment]
I think in the current development phase, this is not necessary. I would start thinking about this as soon as there is a direct requirement.
