### ISSUE TITLE
Jacobian for global variables

### ISSUE THREAD

**Issue by joergfunger** [BAMresearch/BayesianInference#22]
It seems that the Jacobian is not correctly evaluated when multiple individual parameters in a model error (e.g. E0 and E1) are mapped to a single global parameter (assuming E0 and E1 are to be jointly identified). In particular, in the inference problem
```
stacked_jac[:, self.latent[global_name].global_index_range()] = -J
```
stacked Jacobian has the dimension of [out, 1], whereas J has the dimension [out, 2].

**Comment by joergfunger** [comment]
I think I made a mistake the implementation is just working fine.

**Comment by TTitscher** [comment]
I was actually about to tackle this issue and come up with a test case that roughly represents the use case above. AFAI understand, the problem with the dimensions ([out,2] vs [out,1]) is a real issue. If you find the time, can you briefly explain that further?

**Comment by TTitscher** [comment]
@joergfunger As briefly discussed in person, I think the implementation is still incorrect. We currently do
https://github.com/BAMresearch/BayesianInference/blob/master/bayes/inference_problem.py#L175

~~~py
# loop over local_name
   ...
   J = parameter_jac[local_name]
   ...
   stacked_jac[:, self.latent[global_name].global_index_range()] = -J
~~~

Thus, if two `local_names` are mapped to the same `global_name`, one of the Jacobians would simply be overwritten.

A fix _could_ be to simply change the " = -J" to "-= J",

~~~py
   stacked_jac[:, self.latent[global_name].global_index_range()] -= J
~~~

but I would like to see a proper test for that.

(Note that the strange minus was my way to solve #19.)
