### ISSUE TITLE
Separate VB algorithm

### ISSUE THREAD

**Issue by TTitscher** [BAMresearch/BayesianInference#39]
It seems that the focus of this package shifts from being focused on (aka built around) the Chappell VB implementation towards our idea of "convenience code" to define somewhat general inference problems. Nothing against that!

Should we, for clarity, then separate our VB implementation? Especially, if the "convenience code" is about to be moved elsewhere.

**Comment by joergfunger** [comment]
I would rather try to extract the relevant features of our implementation into taralli, only afterwards I would then think about adapting our package again. In the optimal setting, this would then be two additional sub packages in taralli.
