### ISSUE TITLE
Remove sphinx from requirements

### ISSUE THREAD

**Issue by TTitscher** [BAMresearch/BayesianInference#45]
The current requirements contain 
~~~
sphinx
sphinx_rtd_theme
~~~
which are not needed to install the package, e.g. in another project or a CI pipeline. 

To build the documentation locally, we could have a `requirements_website.txt` or so that needs to be installed once by a user. But @joergfunger, how does the readthedocs integration work? I did not find the place that tells readthedocs what to build. I assume, by default, they look for a `conf.py` and `index.rst` and run `sphinx` themselves. Is that correct? In that case, the `requirements_website.txt` plan would work.

**Comment by joergfunger** [comment]
For your first question, I think this is what Readthedocs does. However, you could still create the documentation (e.g. to test before the submission yourself). I think they way to go could be to follow the approach [here](https://packaging.python.org/tutorials/packaging-projects/) that actually splits the requirements into the ones required for using the package and for developing it. There, it might make sense to keep the sphinx related stuff for the development and remove it from the user section. Btw, I tried to incorporate that in a [branch](https://github.com/BAMresearch/BayesianInference/tree/build_conda_package) (that was originally intended to make a conda package, this part is not working, yet, so I haven't made a merge request).

**Comment by TTitscher** [comment]
I could not find much information on that in your first link from python.org. Anyways, on your branch you added the actual dependencies `numpy,scipy` in [setup.cfg](https://github.com/BAMresearch/BayesianInference/blob/build_conda_package/setup.cfg) and the additional packages are in [environment.yml](https://github.com/BAMresearch/BayesianInference/blob/build_conda_package/environment.yml), right?

As an easy fix, I suggest to only have `numpy, scipy` in our current `setup.py` and document somewhere that you need `sphinx, ...` for running `doit website`.
